### ISSUE TITLE
Hash lookup for string search

### ISSUE THREAD

**Issue by mpietras-p4** [Paradigm4/revealcore#21]
```
array:
  ...
  # METADATA_VALUE
  METADATA_VALUE:
    ...
    attributes:
      ontology_category_id: int64
      metadata_value: string
      created: string
      updated: string
    hash_dims:
      metadata_value:
        start: 0
        end: 1048575
        chunk_interval: 256
        overlap: 0
        hashed_attribute: metadata_value
        hash_function: "murmur_hash_32(toupper({{hashed_attribute}})) % 1048576"
    dims:
      metadata_value_id:
        start: 0
        end: Inf
        chunk_interval: 10000
        overlap: 0
    ...
```

some hypothetical search_entity_by_attribute function would know to, if {{attribute}} is
in hash_dims, generate the hash using the hash function and do an extra filter / join

Similarly, hypothetical generic register function would not require hash_dims in input, but
would generate the dim on registration.

Dimension names autogenerated as scidb_hash_dim_{{hashed_attribute}}.
Or maybe just define as normal in dims and have a second entry in hash_dims?

Would require minor changes to schema building functions unless defined explicitly in dims. i.e.:
```
array:
  ...
  # METADATA_VALUE
  METADATA_VALUE:
    ...
    attributes:
      ontology_category_id: int64
      metadata_value: string
      created: string
      updated: string
    hash_dims:
      scidb_hash_dim_metadata_value:
        hashed_attribute: metadata_value
        hash_function: "murmur_hash_32(toupper({{hashed_attribute}})) % 1048576"
    dims:
      metadata_value_id:
        start: 0
        end: Inf
        chunk_interval: 10000
        overlap: 0
      scidb_hash_dim_metadata_value:
        start: 0
        end: 1048575
        chunk_interval: 256
        overlap: 0
    ...
```

**Comment by mpietras-p4** [comment]
Going with the second:
```
array:
  ...
  # METADATA_VALUE
  METADATA_VALUE:
    ...
    attributes:
      ontology_category_id: int64
      metadata_value: string
      created: string
      updated: string
    hash_dims:
      scidb_hash_dim_metadata_value:
        hashed_attribute: metadata_value
        hash_function: "murmur_hash_32(toupper({{hashed_attribute}})) % 1048576"
    dims:
      metadata_value_id:
        start: 0
        end: Inf
        chunk_interval: 10000
        overlap: 0
      scidb_hash_dim_metadata_value:
        start: 0
        end: 1048575
        chunk_interval: 256
        overlap: 0
    ...
```
